spring:
  application:
    name: Live-Config
  kafka:
    consumer:
      client-id:
        config
    bootstrap-servers: localhost:9092,kafka:9092

bootstrap:
  servers: localhost:9092,kafka:9092

server:
  port: 8080

logging:
  level:
    org.springframework: warn
    org.yaml: warn
#startup provides a way of ignoring really old configuration values which are no longer needed.
#This can be because they are obsolete, or because their values have all been updated so there
#is no reason to dig quite so far into the past.
#Valid values are 'Start', 'End', or an integer in the range of 0 to whatever the last position number is.  If
#you set a value higher than the last position number the net effect is to start from the end.
config:
  startup:
    topic: config
    seek: 0
management:
  endpoint:
    health:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true
    logfile:
      enabled: true
    metrics:
      enabled: true
  health:
    rabbit:
      enabled: false
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
    appname: Live-Config
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
