spring:
  kafka:
    consumer:
      group-id:
        myGroup
      client-id:
        config

    bootstrap-servers:
      localhost:9092

logging:
  level:
    org.springframework: warn
    org.yaml: warn
    com.oopuniversity.kafkapoc.config: trace
    com.oopuniversity.kafkapoc: debug

config:
  startup:
    seek: nowhere
